### ISSUE TITLE
Passing shelterType of 'All' to endpoint doesn't return any results

### ISSUE THREAD

**Issue by MC313** [akhan118/shelter-angular-6#3]
**Expected**
- Enpoint: getrequestedinfov2?shelterType
- Parameter: 5
- When calling the endpoint with the specified parameter ('All' shelterType id = 5) all shelters in the database are returned.

**Actual**
- When calling the endpoint with the specified parameter ('All' shelterType id = 5) no shelters are returned even though there are shelters present in the database.

**Comment by isjxique** [comment]
completed in most recent update
but needs to be pushed to server
