### ISSUE TITLE
'ShelterType' attribute isn't returned in the shelter response object

### ISSUE THREAD

**Issue by MC313** [akhan118/shelter-angular-6#4]
When calling the 'getrequestedinfov2?shelterType=2' endpoint the shelterType attribute should be returned along with all other attributes.

**Expected** 
 {
        "shelter_id": "3",
        "shelter_name": "ismaelsss",
        "shelter_address": "safdas",
        "shelter_address_city": "safdas",
        "shelter_address_state": "safdas",
        "shelter_address_zip": "231",
        "shelter_phone": "4123",
        "shelter_long": "4142",
        "shelter_lat": "12",
        "shelter_county": "as",
       ``` 
       "shelter_type": {
              "id": 1,
              "type": "woman"
         }
         ```,
        "available": "1",
        "last_updated": "2018-05-31 05:16:17"
    }

**Actual**
{
        "shelter_id": "3",
        "shelter_name": "ismaelsss",
        "shelter_address": "safdas",
        "shelter_address_city": "safdas",
        "shelter_address_state": "safdas",
        "shelter_address_zip": "231",
        "shelter_phone": "4123",
        "shelter_long": "4142",
        "shelter_lat": "12",
        "shelter_county": "as",
        "available": "1",
        "last_updated": "2018-05-31 05:16:17"
    }

**Comment by akhan118** [comment]
Testing notifications

**Comment by isjxique** [comment]
completed in most recent update
but needs to be pushed to server
